import type { Locale } from "@/content/site";
import type { SizingReasonCode } from "@/types/ac-advisor";
import type { LocalizedText } from "@/types/catalog";

export const advisorOptions = {
  locations: [
    ["ain-sokhna", { ar: "العين السخنة", en: "Ain Sokhna" }],
    ["ras-ghareb", { ar: "رأس غارب", en: "Ras Ghareb" }],
    ["el-gouna", { ar: "الجونة", en: "El Gouna" }],
    ["hurghada", { ar: "الغردقة", en: "Hurghada" }],
    ["safaga", { ar: "سفاجا", en: "Safaga" }],
    ["quseir", { ar: "القصير", en: "Quseir" }],
    ["marsa-alam", { ar: "مرسى علم", en: "Marsa Alam" }],
    ["other", { ar: "موقع آخر", en: "Other location" }],
  ],
  roomTypes: [
    ["bedroom", { ar: "غرفة نوم", en: "Bedroom" }],
    ["living-room", { ar: "غرفة معيشة", en: "Living room" }],
    ["hotel-room", { ar: "غرفة فندقية", en: "Hotel room" }],
    ["office", { ar: "مكتب", en: "Office" }],
    ["clinic", { ar: "غرفة عيادة", en: "Clinic room" }],
    ["shop-showroom", { ar: "محل أو معرض", en: "Shop or showroom" }],
    ["restaurant", { ar: "مطعم أو مطبخ تجاري", en: "Restaurant or commercial kitchen" }],
    ["open-plan", { ar: "مساحة مفتوحة", en: "Open-plan space" }],
    ["other", { ar: "استخدام آخر", en: "Other use" }],
  ],
  installationTypes: [
    ["wall-mounted-split", { ar: "سبليت جداري", en: "Wall-mounted split" }],
    ["concealed-ducted", { ar: "كونسيلد دكت", en: "Concealed ducted" }],
    ["ceiling-cassette", { ar: "كاسيت سقفي", en: "Ceiling cassette" }],
    ["floor-standing", { ar: "دولابي أرضي", en: "Floor standing" }],
    ["unsure-show-all-suitable", { ar: "غير متأكد — اعرض كل الأنظمة المناسبة", en: "Unsure — show all suitable systems" }],
  ],
} as const;

export const advisorReasonCopy: Record<SizingReasonCode, LocalizedText> = {
  "smallest-catalog-capacity": { ar: "١٫٥ حصان هي أصغر قدرة متاحة في الكتالوج؛ يوصى بالتأكيد لتجنب زيادة القدرة.", en: "1.5 HP is the smallest catalog capacity; confirmation is recommended to avoid oversizing." },
  "boundary-proximity": { ar: "النتيجة قريبة من حد قدرة آخر، لذلك تظهر قدرة أعلى كخيار بديل.", en: "The result is close to a capacity boundary, so the next higher capacity is shown as an alternative." },
  "high-sunlight": { ar: "التعرض القوي للشمس رفع الحمل التقديري.", en: "Strong direct sunlight increased the estimated load." },
  "high-ceiling": { ar: "ارتفاع السقف يستدعي تأكيد النتيجة بالمعاينة.", en: "The ceiling height makes site confirmation advisable." },
  "ceiling-out-of-range": { ar: "ارتفاع السقف يتجاوز نطاق الحساب التلقائي المعتمد.", en: "The ceiling height exceeds the approved automatic-calculation range." },
  "top-floor": { ar: "موقع الغرفة في الدور الأخير رفع الحمل التقديري.", en: "The top-floor position increased the estimated load." },
  "roof-exposure": { ar: "التعرض المباشر للسطح مع عزل ضعيف يتطلب معاينة.", en: "Direct roof exposure with poor insulation requires inspection." },
  "large-glazing": { ar: "مساحة الزجاج الكبيرة رفعت الحمل وتستدعي التأكيد.", en: "Large glazing increased the load and should be confirmed." },
  "full-storefront": { ar: "واجهة الزجاج الكاملة تتطلب معاينة فنية.", en: "Full storefront glazing requires a technical inspection." },
  "unknown-insulation": { ar: "حالة العزل غير معروفة، لذلك يوصى بالمعاينة.", en: "Insulation is unknown, so a site inspection is recommended." },
  "poor-insulation": { ar: "العزل الضعيف رفع الحمل التقديري.", en: "Poor insulation increased the estimated load." },
  "room-use-adjustment": { ar: "تم تعديل الحمل حسب استخدام الغرفة.", en: "The load was adjusted for the room use." },
  "high-occupancy": { ar: "عدد الأشخاص المرتفع يستدعي تأكيد القدرة.", en: "High occupancy makes capacity confirmation advisable." },
  "occupancy-out-of-range": { ar: "عدد الأشخاص يتجاوز نطاق الحساب المباشر.", en: "Occupancy exceeds the direct-calculation range." },
  restaurant: { ar: "المطاعم والمطابخ التجارية تحتاج إلى حساب أحمال ومعاينة فنية.", en: "Restaurants and commercial kitchens need a technical load assessment and inspection." },
  "open-plan": { ar: "المساحة المفتوحة تحتاج إلى معاينة لتأكيد توزيع الهواء والقدرة.", en: "The open-plan space needs inspection to confirm air distribution and capacity." },
  "other-room": { ar: "الاستخدام غير القياسي يحتاج إلى تأكيد فني.", en: "The non-standard room use needs technical confirmation." },
  "other-location": { ar: "الموقع خارج القائمة الحالية ويحتاج إلى تأكيد ظروف المناخ والخدمة.", en: "The location is outside the current list and its climate and service conditions need confirmation." },
  "large-area": { ar: "المساحة تتجاوز ٦٠ م²؛ النتيجة مبدئية والمعاينة إلزامية.", en: "The area exceeds 60 m²; the result is preliminary and inspection is mandatory." },
  "area-out-of-range": { ar: "المساحة تتجاوز ١٠٠ م² ولا يتم فرض قدرة تلقائية.", en: "The area exceeds 100 m², so no automatic capacity is forced." },
  "dimensions-out-of-range": { ar: "أحد الأبعاد يتجاوز نطاق الحساب المباشر المعتمد.", en: "One or more dimensions exceed the approved direct-calculation range." },
  "connected-rooms": { ar: "الغرف المتصلة تتطلب معاينة وحساب توزيع الهواء.", en: "Connected rooms require inspection and air-distribution assessment." },
  "irregular-geometry": { ar: "شكل المساحة غير المنتظم يتطلب معاينة.", en: "Irregular room geometry requires inspection." },
  "high-equipment-load": { ar: "الأجهزة أو الإضاءة ذات الحمل المرتفع تتطلب معاينة.", en: "High equipment or lighting heat load requires inspection." },
  "conflicting-preferences": { ar: "لا توجد منتجات تطابق جميع التفضيلات؛ يلزم تأكيد النظام المناسب فنيًا.", en: "No product matches every preference; the suitable system requires technical confirmation." },
  "load-out-of-range": { ar: "الحمل يتجاوز ٦٠٬٠٠٠ BTU ولا يتم فرض قدرة ٧٫٥ حصان.", en: "The load exceeds 60,000 BTU, so 7.5 HP is not forced." },
};

export const advisorCopy = {
  ar: {
    launcher: "مساعد كول بيت الذكي",
    title: "مساعد كول بيت الذكي لاختيار التكييف",
    intro: "أدخل بيانات الغرفة للحصول على توصية مبدئية بالقدرة والمنتجات المناسبة.",
    close: "إغلاق المساعد",
    progress: "الخطوة {current} من 5",
    back: "السابق",
    next: "التالي",
    calculate: "احسب القدرة المقترحة",
    steps: ["الموقع والاستخدام", "الأبعاد والإشغال", "ظروف الحمل الحراري", "التفضيلات", "النتيجة"],
    location: "الموقع",
    roomType: "استخدام الغرفة",
    installation: "نظام التركيب المفضل",
    length: "الطول بالمتر",
    width: "العرض بالمتر",
    height: "ارتفاع السقف بالمتر",
    occupants: "عدد الأشخاص",
    sunlight: "التعرض للشمس",
    floor: "حالة الدور والسطح",
    glazing: "مساحة الزجاج",
    insulation: "جودة العزل",
    coolingMode: "نظام التشغيل",
    technology: "التقنية",
    brand: "العلامة",
    connectedRooms: "المساحة تشمل غرفًا متصلة",
    irregularGeometry: "شكل المساحة غير منتظم",
    highEquipmentLoad: "توجد أجهزة أو إضاءة ذات حمل حراري مرتفع",
    resultTitle: "توصية القدرة المبدئية",
    area: "المساحة",
    volume: "الحجم",
    baseLoad: "الحمل الأساسي",
    adjustedLoad: "الحمل بعد التعديل",
    recommendedHp: "القدرة المقترحة",
    alternativeHp: "قدرة بديلة",
    noAutomaticHp: "لا توجد قدرة تلقائية آمنة لهذه البيانات",
    directOptions: "خيارات مباشرة للغرفة",
    inspectionOptions: "أنظمة قد تكون مناسبة بعد المعاينة",
    noMatches: "لا توجد منتجات مطابقة لكل التفضيلات الحالية.",
    modelCodes: "الموديلات",
    customerName: "الاسم (اختياري)",
    selectProduct: "اختر منتجًا لإضافته إلى الرسالة (اختياري)",
    noProduct: "بدون منتج محدد",
    viewProducts: "عرض المنتجات المطابقة",
    whatsapp: "اطلب تأكيدًا عبر واتساب",
    inspection: "اطلب معاينة فنية",
    startAgain: "ابدأ من جديد",
    disclaimer: "هذه توصية مبدئية بناءً على البيانات المدخلة، ولا تعتبر حساب أحمال هندسيًا نهائيًا. يجب تأكيد القدرة المناسبة بعد المعاينة الفنية للموقع.",
    privacy: "لا يتم حفظ الإجابات. تُرسل البيانات فقط عند اختيار فتح واتساب.",
    unavailable: "خدمة واتساب غير متاحة حاليًا.",
    checkpointKicker: "مساعد اختيار التكييف",
    checkpointTitle: "مش عارف تختار التكييف المناسب؟",
    checkpointCopy: "أدخل بيانات الغرفة وسيقترح مساعد كول بيت القدرة والخيارات المناسبة.",
    checkpointCta: "ابدأ مع مساعد كول بيت",
  },
  en: {
    launcher: "CoolPet Smart Advisor",
    title: "CoolPet Smart AC Advisor",
    intro: "Enter the room details for a preliminary capacity and product recommendation.",
    close: "Close advisor",
    progress: "Step {current} of 5",
    back: "Back",
    next: "Next",
    calculate: "Calculate suggested capacity",
    steps: ["Location and use", "Dimensions and occupancy", "Heat-load conditions", "Preferences", "Result"],
    location: "Location",
    roomType: "Room use",
    installation: "Preferred installation system",
    length: "Length in metres",
    width: "Width in metres",
    height: "Ceiling height in metres",
    occupants: "Occupants",
    sunlight: "Sun exposure",
    floor: "Floor and roof condition",
    glazing: "Glazing level",
    insulation: "Insulation quality",
    coolingMode: "Operating mode",
    technology: "Technology",
    brand: "Brand",
    connectedRooms: "The space includes connected rooms",
    irregularGeometry: "The room has irregular geometry",
    highEquipmentLoad: "The space has unusually high equipment or lighting heat load",
    resultTitle: "Preliminary capacity recommendation",
    area: "Area",
    volume: "Volume",
    baseLoad: "Base load",
    adjustedLoad: "Adjusted load",
    recommendedHp: "Recommended capacity",
    alternativeHp: "Alternative capacity",
    noAutomaticHp: "No safe automatic capacity is available for these inputs",
    directOptions: "Direct room options",
    inspectionOptions: "Systems that may be suitable after inspection",
    noMatches: "No products match every current preference.",
    modelCodes: "Models",
    customerName: "Name (optional)",
    selectProduct: "Add a product to the message (optional)",
    noProduct: "No specific product",
    viewProducts: "View matching products",
    whatsapp: "Request confirmation on WhatsApp",
    inspection: "Request site inspection",
    startAgain: "Start again",
    disclaimer: "This is a preliminary recommendation based on the information provided and is not a final engineering load calculation. The required capacity should be confirmed through a professional site inspection.",
    privacy: "Answers are not stored. Data is sent only when you choose to open WhatsApp.",
    unavailable: "WhatsApp is currently unavailable.",
    checkpointKicker: "AC selection advisor",
    checkpointTitle: "Not sure which AC is right for you?",
    checkpointCopy: "Enter your room details and CoolPet will suggest a preliminary capacity and suitable options.",
    checkpointCta: "Start with CoolPet",
  },
} as const satisfies Record<Locale, Record<string, string | readonly string[]>>;
