import type { ProductFamily } from "@/types/catalog";

const copy = (ar: string, en: string) => ({ ar, en });
const commonHighlights = [copy("موديلات متعددة داخل العائلة", "Multiple model configurations"), copy("السعر الحالي متاح عند الطلب", "Current price available on request")];

export const productFamilies: ProductFamily[] = ([
  { id: "carrier-xcool-inverter", slug: "xcool-inverter", brand: "carrier", name: copy("XCOOL إنفرتر", "XCOOL Inverter"), productType: "wall-mounted-split", marketSegments: ["residential"], technology: "inverter", refrigerant: "R32", description: copy("عائلة سبليت حائطية بتقنية الإنفرتر ومبرد R32.", "Wall-mounted split family with inverter technology and R32 refrigerant."), highlights: commonHighlights, familyImagePath: "/products/catalog/carrier/xcool-inverter.webp", assetAuthorization: "approved", featured: true, displayOrder: 1 },
  { id: "carrier-optimax-inverter", slug: "optimax-inverter", brand: "carrier", name: copy("Optimax إنفرتر", "Optimax Inverter"), productType: "wall-mounted-split", marketSegments: ["residential", "commercial"], technology: "inverter", refrigerant: "R410A", description: copy("عائلة سبليت حائطية إنفرتر بمبرد R410A.", "Wall-mounted inverter family using R410A refrigerant."), highlights: commonHighlights, familyImagePath: "/products/catalog/carrier/optimax-inverter.webp", assetAuthorization: "approved", featured: false, displayOrder: 2 },
  { id: "carrier-optimax-pro", slug: "optimax-pro", brand: "carrier", name: copy("Optimax Pro", "Optimax Pro"), productType: "wall-mounted-split", marketSegments: ["residential", "commercial"], technology: "fixed-speed", refrigerant: "R410A", description: copy("عائلة سبليت حائطية ثابتة السرعة بمبرد R410A.", "Fixed-speed wall-mounted split family using R410A refrigerant."), highlights: commonHighlights, familyImagePath: "/products/catalog/carrier/optimax-pro.webp", assetAuthorization: "approved", featured: true, displayOrder: 3 },
  { id: "carrier-xcool", slug: "xcool", brand: "carrier", name: copy("XCOOL", "XCOOL"), productType: "wall-mounted-split", marketSegments: ["residential"], technology: "fixed-speed", refrigerant: "R32", description: copy("عائلة سبليت حائطية ثابتة السرعة بمبرد R32.", "Fixed-speed wall-mounted split family using R32 refrigerant."), highlights: commonHighlights, familyImagePath: null, assetAuthorization: "pending", featured: false, displayOrder: 4 },
  { id: "carrier-classicool-inverter", slug: "classicool-inverter", brand: "carrier", name: copy("ClassiCool إنفرتر", "ClassiCool Inverter"), productType: "concealed-ducted", marketSegments: ["commercial", "projects"], technology: "inverter", refrigerant: "R410A", description: copy("عائلة تكييف مخفي ودكت بتقنية الإنفرتر.", "Concealed ducted family with inverter technology."), highlights: commonHighlights, familyImagePath: "/products/catalog/carrier/classicool-inverter.webp", assetAuthorization: "approved", featured: true, displayOrder: 5 },
  { id: "carrier-classicool-pro", slug: "classicool-pro", brand: "carrier", name: copy("ClassiCool Pro", "ClassiCool Pro"), productType: "concealed-ducted", marketSegments: ["commercial", "projects"], technology: "fixed-speed", refrigerant: "R410A", description: copy("عائلة تكييف مخفي ودكت ثابتة السرعة.", "Fixed-speed concealed ducted family."), highlights: commonHighlights, familyImagePath: "/products/catalog/carrier/classicool-pro.webp", assetAuthorization: "approved", featured: false, displayOrder: 6 },
  { id: "carrier-decor-inverter", slug: "decor-inverter", brand: "carrier", name: copy("DÉCOR إنفرتر", "DÉCOR Inverter"), productType: "ceiling-cassette", marketSegments: ["commercial", "projects"], technology: "inverter", refrigerant: "R410A", description: copy("عائلة كاسيت سقفية بتقنية الإنفرتر.", "Ceiling cassette family with inverter technology."), highlights: commonHighlights, familyImagePath: "/products/catalog/carrier/decor-inverter.webp", assetAuthorization: "approved", featured: false, displayOrder: 7 },
  { id: "carrier-elegant-inverter", slug: "elegant-inverter", brand: "carrier", name: copy("Elegant إنفرتر", "Elegant Inverter"), productType: "floor-standing", marketSegments: ["commercial", "projects"], technology: "inverter", refrigerant: "R410A", description: copy("عائلة تكييف دولابي بتقنية الإنفرتر.", "Floor-standing family with inverter technology."), highlights: commonHighlights, familyImagePath: "/products/catalog/carrier/elegant-inverter.webp", assetAuthorization: "approved", featured: false, displayOrder: 8 },
  { id: "carrier-elegant-pro", slug: "elegant-pro", brand: "carrier", name: copy("Elegant Pro", "Elegant Pro"), productType: "floor-standing", marketSegments: ["commercial", "projects"], technology: "fixed-speed", refrigerant: "R410A", description: copy("عائلة تكييف دولابي ثابتة السرعة.", "Fixed-speed floor-standing family."), highlights: commonHighlights, familyImagePath: null, assetAuthorization: "pending", featured: false, displayOrder: 9 },
  { id: "midea-ai-ecomaster-inverter", slug: "ai-ecomaster-inverter", brand: "midea", name: copy("AI ECOMASTER إنفرتر", "AI ECOMASTER Inverter"), productType: "wall-mounted-split", marketSegments: ["residential"], technology: "inverter", refrigerant: "R32", description: copy("عائلة سبليت حائطية بتقنية الإنفرتر ومبرد R32.", "Wall-mounted split family with inverter technology and R32 refrigerant."), highlights: commonHighlights, familyImagePath: "/products/catalog/midea/ai-ecomaster-inverter.webp", assetAuthorization: "approved", featured: true, displayOrder: 10 },
  { id: "midea-mission-inverter", slug: "mission-inverter", brand: "midea", name: copy("Mission إنفرتر", "Mission Inverter"), productType: "wall-mounted-split", marketSegments: ["residential", "commercial"], technology: "inverter", refrigerant: "R410A", description: copy("عائلة سبليت حائطية إنفرتر بمبرد R410A.", "Wall-mounted inverter family using R410A refrigerant."), highlights: commonHighlights, familyImagePath: "/products/catalog/midea/mission-inverter.webp", assetAuthorization: "approved", featured: false, displayOrder: 11 },
  { id: "midea-xtreme-pro", slug: "xtreme-pro", brand: "midea", name: copy("XTreme Pro", "XTreme Pro"), productType: "wall-mounted-split", marketSegments: ["residential"], technology: "fixed-speed", refrigerant: "R32", description: copy("عائلة سبليت حائطية ثابتة السرعة بمبرد R32.", "Wall-mounted split family using R32 refrigerant."), highlights: commonHighlights, familyImagePath: "/products/catalog/midea/xtreme-pro.webp", assetAuthorization: "approved", featured: true, displayOrder: 12 },
  { id: "midea-mission-pro", slug: "mission-pro", brand: "midea", name: copy("Mission Pro", "Mission Pro"), productType: "wall-mounted-split", marketSegments: ["residential", "commercial"], technology: "fixed-speed", refrigerant: "R410A", description: copy("عائلة سبليت حائطية ثابتة السرعة بمبرد R410A.", "Fixed-speed wall-mounted split family using R410A refrigerant."), highlights: commonHighlights, familyImagePath: null, assetAuthorization: "pending", featured: true, displayOrder: 13 },
] satisfies ProductFamily[]).sort((a, b) => a.displayOrder - b.displayOrder);

export const featuredProductFamilies = productFamilies.filter((family) => family.featured).slice(0, 6);
