export type Locale = "ar" | "en";

export const company = {
  name: { ar: "كاريير ميديا البحر الأحمر", en: "Carrier–Midea Red Sea" },
  status: { ar: "الوكيل الحصري المعتمد لكاريير وميديا في البحر الأحمر", en: "Authorized exclusive Carrier and Midea dealer in the Red Sea" },
  territory: { ar: "العين السخنة ومحافظة البحر الأحمر", en: "Ain Sokhna and the Red Sea Governorate" },
  address: {
    ar: {
      formatted: "طريق النصر، أمام بنك سي أي بي (CIB)، الغردقة، البحر الأحمر، مصر",
      streetAddress: "طريق النصر، أمام بنك سي أي بي (CIB)",
      addressLocality: "الغردقة",
      addressRegion: "البحر الأحمر",
    },
    en: {
      formatted: "El Nasr Road, opposite CIB Bank, Hurghada, Red Sea, Egypt",
      streetAddress: "El Nasr Road, opposite CIB Bank",
      addressLocality: "Hurghada",
      addressRegion: "Red Sea",
    },
    addressCountry: "EG",
  },
} as const;

export const content = {
  ar: {
    dir: "rtl" as const,
    nav: ["الرئيسية", "التكييفات", "خدماتنا", "مشروعاتنا", "عن الشركة"],
    eyebrow: "حلول مناخية موثوقة منذ اليوم الأول",
    titleA: "راحة استثنائية.",
    titleB: "في كل موسم.",
    intro: "حلول كاريير وميديا المتكاملة للبيع والتركيب وخدمات ما بعد البيع في العين السخنة ومحافظة البحر الأحمر.",
    buy: "اشتري تكييف",
    service: "اطلب خدمة",
    call: "اتصل بنا",
    trust: ["استجابة سريعة", "فنيون متخصصون", "قطع غيار أصلية", "تغطية واسعة"],
    servicesKicker: "خدمة متكاملة",
    servicesTitle: "خبرة تقنية تريح بالك",
    servicesSub: "من أول معاينة وحتى الصيانة الدورية، فريق واحد مسؤول عن جودة التجربة بالكامل.",
    services: [
      ["01", "التركيب والتأسيس", "معاينة دقيقة، اختيار القدرة المناسبة، وتركيب يحافظ على كفاءة جهازك."],
      ["02", "الصيانة والإصلاح", "تشخيص واضح وإصلاحات موثوقة للأعطال الشائعة والمعقدة."],
      ["03", "التنظيف العميق", "تنظيف احترافي يحسن جودة الهواء ويستعيد كفاءة التبريد."],
      ["04", "العقود السنوية", "زيارات وقائية مجدولة للفلل، الشركات، الفنادق والمنتجعات."],
    ],
    territoryKicker: "من السخنة إلى مرسى علم",
    territoryTitle: "نغطي ساحل البحر الأحمر",
    territoryText: "فرقنا تصل إليك أينما كنت، بخدمة منظمة ومواعيد واضحة.",
    cities: ["العين السخنة", "رأس غارب", "الغردقة", "الجونة", "سفاجا", "القصير", "مرسى علم"],
    quoteKicker: "ابدأ الآن",
    quoteTitle: "اطلب عرض سعر أو احجز صيانة",
    quoteText: "أرسل التفاصيل الأساسية وسنجهزها لك في رسالة واتساب منظمة لتبدأ المحادثة مباشرة.",
    name: "الاسم",
    phone: "رقم الهاتف",
    area: "المنطقة",
    need: "نوع الطلب",
    needOptions: ["شراء تكييف", "تركيب", "صيانة", "إصلاح", "تنظيف", "عقد سنوي"],
    details: "اكتب التفاصيل أو وصف المشكلة",
    send: "إرسال عبر واتساب",
    placeholderName: "مثال: أحمد محمد",
    placeholderPhone: "01xxxxxxxxx",
    placeholderArea: "مثال: الغردقة",
    footerText: "مبيعات • تركيب • صيانة • خدمات ما بعد البيع",
    rights: "كاريير–ميديا البحر الأحمر. جميع الحقوق محفوظة.",
  },
  en: {
    dir: "ltr" as const,
    nav: ["Home", "Products", "Services", "Projects", "About"],
    eyebrow: "Trusted climate solutions, from day one",
    titleA: "Exceptional comfort.",
    titleB: "Every season.",
    intro: "Integrated Carrier and Midea sales, installation, and after-sales service across Ain Sokhna and the Red Sea.",
    buy: "Buy an AC",
    service: "Request service",
    call: "Call us",
    trust: ["Fast response", "Specialist technicians", "Original spare parts", "Wide coverage"],
    servicesKicker: "End-to-end service",
    servicesTitle: "Technical expertise. Total peace of mind.",
    servicesSub: "From the first inspection to preventive care, one team owns the quality of your entire experience.",
    services: [
      ["01", "Installation & fit-out", "Accurate inspection, capacity selection, and installation that protects efficiency."],
      ["02", "Maintenance & repair", "Clear diagnosis and dependable repairs for simple and complex faults."],
      ["03", "Deep cleaning", "Professional cleaning that improves air quality and restores cooling performance."],
      ["04", "Annual contracts", "Scheduled preventive visits for villas, companies, hotels and resorts."],
    ],
    territoryKicker: "From Sokhna to Marsa Alam",
    territoryTitle: "We cover the Red Sea coast",
    territoryText: "Our teams reach you with organized service and clear appointment times.",
    cities: ["Ain Sokhna", "Ras Gharib", "Hurghada", "El Gouna", "Safaga", "Quseir", "Marsa Alam"],
    quoteKicker: "Get started",
    quoteTitle: "Request a quote or book service",
    quoteText: "Share the essentials and we will turn them into a structured WhatsApp message to start your conversation.",
    name: "Name",
    phone: "Phone number",
    area: "Area",
    need: "What do you need?",
    needOptions: ["Buy an AC", "Installation", "Maintenance", "Repair", "Cleaning", "Annual contract"],
    details: "Add details or describe the issue",
    send: "Send via WhatsApp",
    placeholderName: "e.g. Ahmed Mohamed",
    placeholderPhone: "01xxxxxxxxx",
    placeholderArea: "e.g. Hurghada",
    footerText: "Sales • Installation • Maintenance • After-sales",
    rights: "Carrier–Midea Red Sea. All rights reserved.",
  },
};
