export type LocalizedText = { ar: string; en: string };
export type ProductBrand = "carrier" | "midea";
export type ProductCapacity = 1.5 | 2.25 | 3;
export type CoolingMode = "cool-only" | "cool-heat";
export type ProductTechnology = "fixed-speed" | "inverter";

export type Product = {
  id: string;
  slug: string;
  brand: ProductBrand;
  series: string;
  modelCode: string;
  name: LocalizedText;
  description: LocalizedText;
  capacityHp: ProductCapacity;
  coolingMode: CoolingMode;
  technology: ProductTechnology;
  energyClass?: string;
  warrantyYears?: number;
  image: string;
  featured: boolean;
  recommended: boolean;
  displayOrder: number;
  active: boolean;
  priceMode: "request-quote";
  sourceUrl: string;
  verifiedAt: string;
  requiresClientConfirmation: boolean;
  assetAuthorization: "pending" | "approved";
};
